<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <WorkspaceStartup>true</WorkspaceStartup>
        <ApplicationIcon>../../res/Icon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Rombadil\Rombadil.csproj" />
    </ItemGroup>

</Project>
